spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/todolist
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create

#logging:
#    level:
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

decorator:
    datasource:
        p6spy:
            enable-logging: true

jwt:
    secret-key: "fasdfasasdflknewqiofdsalkfnqwouie234231412fkdsjafbeuwqpfbdsadflfbasfklwuiqefblskf34214asdkljfbsaldrasdrkljfb"
    access-token-expire-time: 1000 * 60 * 60 * 2
    refresh-token-expire-time: 1000 * 60 * 60 * 24 * 7

# validation message
custom:
    validation:
        content:
            not-blank: "내용을 입력해주세요."