spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/todolist
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create
            batch_size: 100

decorator:
    datasource:
        p6spy:
            enable-logging: true

jwt:
    secret-key: "fasdfasasdflknewqiofdsalkfnqwouie234231412fkdsjafbeuwqpfbdsadflfbasfklwuiqefblskf34214asdkljfbsaldrasdrkljfb"
    access-token-expire-time: 72000000
    refresh-token-expire-time: 604800000